README.md

It's linking to https://github.com/phoenixframework/phoenix_html/blob/master/hexdocs.pm/phoenix_html right now.

Fix docs url in README

---

lib/phoenix_html/engine.ex
test/phoenix_html/engine_test.exs

ref: https://github.com/phoenixframework/phoenix/issues/879
@josevalim I expected this to be more work. I am post walking the body and rewriting `Dict.get(var!(assigns), var)` to `Dict.fetch!(var!(assigns), var)`. Do we need anything more? Are there edgecases I'm missing? Should we raise our own more helpful error?

Raise on missing assigns

---

lib/phoenix_html/link.ex
test/phoenix_html/link_test.exs

When calling link/2 like `link("Logout", "/logout")`, you get the ff error `no function clause matching in Keyword.pop/3`. This PR just raises a clearer error message when the 2nd arg to `link/2` is not a keyword list.

Clearer error message when 2nd arg to link/2 is not a keyword list

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

I believe is pretty common to have label text content the same as the field name.
Example, I keep doing this a lot:
```erb
<%= text_input f, :first_name,  "First name" %>
<%= text_input f, :middle_name, "Middle name" %>
<%= text_input f, :last_name,   "Last name" %>
<%= text_input f, :gender,      "Gender" %>
```
So I thought it was a good idea to improve the helper so the label text content can be inferred from the actual field.

Allow default text content on labels to be inferred from field

---

lib/phoenix_html/form.ex

Does this option mean `append` ? Because `prepend` already described just above line.

fix option in inputs_for doc

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This makes it easier to follow the guidelines of several front-end frameworks that suggest to have controls inside of their label in certain cases (see http://getbootstrap.com/css/#forms or http://foundation.zurb.com/docs/components/forms.html).

Add block option for label tags

---

lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs

Found this while trying to build and unordered list here: https://github.com/mgwidmann/scrivener_html/blob/master/lib/scrivener/html.ex#L112

Nested & attr-less content_tag throws exception

---

lib/phoenix_html/link.ex
test/phoenix_html/link_test.exs

Its very confusing when the `:to` option was provided but it says that it was not provided (but that actually the code cannot tell that the value was `nil`)
This improves the error message and returns the options to the user so that they can decipher for themselves what went wrong. In the case where nil was provided, it will be more obvious.

link("here", to: nil) says :to was not provided

---

lib/phoenix_html/form.ex

1. "three distinct scenario" => "three distinct scenarios"
2. Eplain that inputs will be set to values from the request params for
connection data forms
3. Explain what the `:enforce_utf8` option does when it's not disabled.

Minor additions to the docs for `Phoenix.HTML.Form`

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This allows the multiple_select/4 function to preserve the values that were submitted to the model.
This resolves issue #32

Should preserve the field value in multiple_select

---

lib/phoenix_html/engine.ex
test/phoenix_html/engine_test.exs

This is an alternative approach to my previous pull request, phoenixframework/phoenix#1342.  I'm submitting this because I found the framework behavior surprising and it took me a while to figure it out. I understand the motivation for not accepting my previous PR, so I'm hopeful that this log message will save time for others who encounter a similar issue.
I'm not 100% confident in the terminology I chose (parent vs. child view template), so please feel free to offer alternative wording suggestions.

Try to hint why an expected view assign is missing

---

lib/phoenix_html.ex
lib/phoenix_html/format.ex
test/phoenix_html/format_test.exs

Because I recently needed this functionality I implemented it in a package [simple_format](https://github.com/michalmuskala/simple_format), but @josevalim advised adding it directly to `Phoenix.HTML`. So here it is :smiley:

Add Phoenix.HTML.Format.text_to_html/2

---

lib/phoenix_html/form.ex

In the section of "With model data" for the `Phoenix.HTML.Form` docs, in the definition of the `User.changeset/2` function, the example calls a `cast/2` function but I think that the intention here is to call the `Ecto.Changeset.cast/4` function. Is that is the case this change could help.

Fix for cast example in Phoenix.HTML.Form docs

---

lib/phoenix_html/form.ex

From this changelog:
https://gist.github.com/chrismccord/557ef22e2a03a7992624
`Ecto.Model` was changed to `Ecto.Schema`
This commit changes that usage in the documentation for
form.ex.

Documentation changes for Phoenix 1.1

---

lib/phoenix_html/safe.ex
test/phoenix_html/safe_test.exs

Since this is very specific, I don't have great hopes that it'll be merged as-is.
But I've seen people on Slack that were bit by this, three times in the last few days, and I haven't even been looking. So I'm thinking a small, simple fix that we can remove by Phoenix 2 or earlier can be a cheap way of avoiding some upgrade pain.

More helpful error when missing translate_error

---

lib/phoenix_html/link.ex

The data-confirm attribute is supported by phoenix_html.js, but instructions for generating the confirm attribute was lacking. This adds an example and adds more explicit direction for adding data attributes.
Additionally, it seems fitting to me that passing a bare `confirm` keyword would automatically generate the `data-confirm` attribute. I originally intended to add support for it, but decided on documenting the current situation instead. If supporting `confirm` directly is preferred/desired, I can add that as well and update the PR.

Enhance documentation for data-confirm attribute

---

test/phoenix_html/inputs_for_test.exs

A test to prove file_input does not work together with inputs_for as mention in Bug #70.
`safe_inputs_for` is a bit problematic as the opts are put in inputs_for and I required an option for form_for. I hope to find time to be able to fix the problem it self.

Test to prove input_for does not work with file_input

---

lib/phoenix_html/tag.ex

Example usage of `form_tag` had "get" in arguments, but "post" in output.

Fix form tag example code

---

lib/phoenix_html.ex

Fixes the formatting seen here: https://hexdocs.pm/phoenix_html/Phoenix.HTML.html#macros

Fix docs: escape interpolation

---

lib/phoenix_html/safe.ex

I've been reading the code and found one little spelling mistake. Here's my humble contribution.

Fix a typo in to_iodata error message

---

CHANGELOG.md

As of [this commit](https://github.com/phoenixframework/phoenix_html/commit/1c1ee243583f79eefbbb4655dbbd8e287eb21821), `:min`, `:sec` option in `Phoenix.HTML.Form.datetime_select/3` (or `Phoenix.HTML.Form.time_select/3`) are no longer supported. This change breaks code in older version. For example:
```elixir
<%= datetime_select form, :born_at, builder: fn b -> %>
Date: <%= b.(:day, []) %> / <%= b.(:month, []) %> / <%= b.(:hour, []) %>
Time: <%= b.(:hour, []) %> : <%= b.(:min, []) %>
<% end %>
```
Error output:
```
** (exit) an exception was raised:
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Phoenix.HTML.Form.datetime_builder/5
(phoenix_html) lib/phoenix_html/form.ex:1002: anonymous fn(:min, []) in Phoenix.HTML.Form.datetime_builder/5
```

Add Phoenix.HTML.Form backwords incompatible changes in CHANGELOG

---

priv/static/phoenix_html.js
web/static/js/phoenix_html.js

Fix for #96 by checking for a matching parent to support both dynamically added `a[data-submit=parent]` links and those that have child elements that can be the target of the click event.

handle elements nested inside data-submit anchor tags

---

lib/phoenix_html/form.ex

I was looking at the documentation for `field_value` yesterday and was pretty puzzled by this optional `selected` argument for two reasons:
1. The documentation referred both to the `selected` and the `default` argument.
2. The `field_value` is used when fetching values for all inputs, not only for select boxes.
So I decided to make this change. Hopefully it makes sense. ;)

Change arg name and documentation for field_value

---

priv/static/phoenix_html.js
web/static/js/phoenix_html.js

The JavaScript was changed in https://github.com/phoenixframework/phoenix_html/pull/77 to use `Element.matches` to find the correct element. Unfortunately, phantomjs doesn't provide that function.
This fixes that by matching the element manually.

Fix submit links in phantomjs

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

It seems to support the two other version that @josevalim suggested did already work. The only thing needed was to easy the guard on line 738 of lib/phoenix_html/form.ex to also allow for maps
I've added two more tests that cover the suggested syntax and merged the current master of phoenixframework/phoenix_html.
I've tested this on one of my own projects and everything seems fine.
Thank you @ciaran for the main work :)

Support for suggested syntax by @josevalim

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Adds a `grouped_select` form helper, which takes a map of group labels => options lists, and creates a select with `<optgroup>` tags.

Add `grouped_select` form helper.

---

lib/phoenix_html/form.ex

I was struggling to find out how to actually map a list of ecto schema's to the select tag method and I found it strange that such a common use case was not mentioned in the docs. So I tried to fix that :)

Add example for a list of ecto schema's to select

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This utilizes the `content_tag` option for taking a `do` block. The primary use case we're looking to cover is putting an SVG inside the button such as:
```elixir
<%= submit do %>
<%= content_tag(:svg) %>
<% end %>
```

Allow the submit to take a `do` option

---

lib/phoenix_html/link.ex
test/phoenix_html/link_test.exs

This brings the `button` function in line with the change made in #95 and keeps us consistently using the `button` tag instead of the `input` tag. Also the fact that the `button` function doesn't return a button just seems weird 😄 
It also makes it easier for my next proposed change which is going to be allowing a `do:` option on the `button` function.

Use a button instead of an input for the button/2

---

lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs

As Phoenix is js agnostic there is not much js tools outbox as in Rails. So I've made a port of jquery-ujs for phoenix - [phoenix_ujs](https://github.com/jalkoby/phoenix_ujs). 
The only problem is that phoenix_ujs doesn't have csrf meta tag helpers, so I've added it. Plus this helper tell about other "magic" params which phoenix_html expects.

Add csrf_meta_tag helper

---

lib/phoenix_html/link.ex
test/phoenix_html/link_test.exs

We often wrap a button around svgs for things like deleting a model. This would give us markup something like:
```html
<button class="delete-icon-button">
<svg>
<use xlink:href="#icon-cancel-circle">
</svg>
</button>
```
now this could be used with phoenix:
```html
<%= button to: "/", class: "delete-icon-button" do %>
<svg>
<use xlink:href="#icon-cancel-circle">
</svg>
<% end %>
```
One thing to note: we are passing in `{:safe, do_option}` so that the given option is not HTML escaped. This is a bit of a security issue but I can't imagine a situation where you wouldn't want that functionality. I don't think it makes sense to require `{:safe, "<p>Hi</p>}` inside the `do` option.

Allow passing a `do:` option to the button function

---

lib/phoenix_html/form.ex

Hi! It seems like the typespec for [`Phoenix.HTML.Form.input_validations/2`](https://github.com/phoenixframework/phoenix_html/blob/30c437b231ca48516097e166ae4fddb95bfd8b81/lib/phoenix_html/form.ex#L282) should be changed to `Keyword.t` as the return type, to match up with [`Phoenix.HTML.FormData.input_validations/2`](https://github.com/phoenixframework/phoenix_html/blob/9efece91e4c77df97e0e95087d35ef18f05af0f4/lib/phoenix_html/form_data.ex#L33).

Mismatching typespec for Phoenix.HTML.Form.input_validations/2

---

priv/static/phoenix_html.js

Hi! I'm not positive this is the right thing to do, but it solved a problem for me.
Say I have a template like this:
```
<%= form_for ... do %>
<div id="foo">
<%= link to: "/somewhere", class: "fa fa-save", data: [submit: "parent"] %>
</div>
<% end %>
```
(I use `<a>` instead of `<submit>`  because I need to style the submit button with font-awesome icons e.g.)
With the original code, it tried to submit its immediate parent`div#foo`, which of course doesn't work. This PR looks for the nearest parent that is a form and submits that.

Submit nearest form even if not direct descendent

---

lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs

Fixes #129 
I wasn't sure if I should go with `img` or `img_tag`. The `button/2` function doesn't have `_tag`, nor does `form_for`. I think personally I prefer it without the unnecessary `_tag` but I could argue either way!

Add img/2 function for img tags

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Avoid `(FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_value/2` if field is not an atom.
According [this discussion](https://github.com/phoenixframework/phoenix_html/issues/140).

Remove guard is_atom(field) from input_value/2 without form, add tests

---

mix.lock

This PR upgrade Plug from 1.0 to 1.3 to fix a Elixir 1.4 deprecation.
```
warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
lib/plug/request_id.ex:59
```

Upgrade plug 1.3.0 (crypto:rand_bytes/1 deprecation)

---

.travis.yml

This PR adds Elixir 1.4 and latest OTP 19.2 to the travis ci test suite.
Cheers.

Test against Elixir 1.4

---

lib/phoenix_html/form.ex

I saw someone asking how to set a class on a form and not
finding anything about it in the documentation. I thought
this is a common enough thing that we should add it to the
documentation.
Amos King @adkron <amos@binarynoggin.com>

Adds clarification of extra options on `form_for`

---

lib/phoenix_html/form.ex

A small documentation patch to clarify that `select/4` should not be used to create multiple selection elements; `multiple_select/4` should be used instead.
As per @josevalim's [suggestion](https://github.com/phoenixframework/phoenix_html/pull/147#issuecomment-283939145).

Offer advice in documentation of select/4 for creating multiple selects

---

lib/phoenix_html/form.ex

We could use the newer pad_leading but that would break compatibility
with Elixir < 1.3

Remove Elixir 1.5 deprecation warning

---

lib/phoenix_html/form.ex

As the docs use `~S"""..."""` by convention, and the example sigil shown
in these docs was also trying to use `"""` as its delimiter, a `\` had
been inserted to avoid breaking out of the original string.
This of course meant the `\` was rendering in the documentation, which
seems less than ideal (you can see this in action at
https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#datetime_select/3).
Fixed by using an alternative delimiter. I picked `'''`, which is
hopefully not too controversial?

Change sigil_e delimiter for improved documentation rendering

---

lib/phoenix_html/tag.ex

Add additional content_tag documentation to clarify how to use options
with a pointer tag examples.
Relates to #120.

Improve content_tag documentation

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Passing a type other than binary to `Phoenix.HTML.Form.textarea/3` as the `value` option raises an error:
```
** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: ...
```
**Expected behavior:** the function should accept any data structure that implements the `Phoenix.HTML.Safe` protocol.
This seems like an easy fix to me, but I might be missing something important, so any feedback is appreciated :smiley:

Fix ArgumentError in Phoenix.HTML.Form.textarea/3

---

lib/phoenix_html/link.ex
priv/static/phoenix_html.js
test/phoenix_html/link_test.exs
web/static/js/phoenix_html.js

Links with a `:method` other than `:get` no longer create inline forms.
This caused issues with nesting as layed out in #151. Now the forms are
generated, appended to the end of `<body>`, and submitted via Javascript
when the link is clicked.
The new links -- with the options set -- are rendered as follows: `<a
href="#" data-csrf="#{csrf_token}" data-method="#{method}"
data-to="#{to}">#{text}</a>`.
As part of this change `data-submit="parent"` is deprecated, and
`data-method="#{method}"` and `data-csrf="#{csrf_token}"` are introduced.

Fixed behavior of links (#151)

---

lib/phoenix_html/link.ex
lib/phoenix_html/tag.ex
mix.exs
test/phoenix_html/csrf_test.exs

**Work In Progress**
The current implementation is tied up to Plug's CSRF protection code. We need some flexibility around the form-related helpers to, for example, generate a CSRF token input compatible with other frameworks or generate a blank token, so the final HTML output is cacheable.

Allow specifying a custom CSRF token generator

---

priv/static/phoenix_html.js

With this change, creating a button/link with `method: "get"` causes the generated form to issue a corresponding GET request.

Wrap button/link with data-method="get" in form with same method

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

PR #149 introduced a regression in `datetime_builder/5` - the HTML in the `<option>` tag for the "9th day of the month" is rendered inconsistently when compared to the option tags for days 1 to 8.
Current behaviour:
```html
...
<option value="7">07</option>
<option value="8">08</option>
<option value="9">9</option>
<option value="9">10</option>
...
```
Corrected behaviour (i.e. "9" should be "09")
```html
...
<option value="7">07</option>
<option value="8">08</option>
<option value="9">09</option>
<option value="9">10</option>
...
```
I have corrected the source-code in `lib/phoenix_html/form.ex`, and also added to some of the existing test scenarios in `test/phoenix_html/form_test.exs` to test the solution.

Correct datetime_builder/5 for [9th day of month] option tag

---

lib/phoenix_html/link.ex
test/phoenix_html/link_test.exs

This is a PR to allow conversation to continue, but isn't yet complete. The current implementation only raises for "link", but I suspect we will also want to do so for "button"?  
I went with a [whitelist approach](https://security.stackexchange.com/questions/148428/which-url-schemes-are-dangerous-xss-exploitable). And I also added a start to the tuples allowing javascript or data URIs. It is currently only:
```
defp invalid_destination?(to) when is_tuple(to), do: false
```
Do we want to implement the functionality to transform `{:javascript, val}` within the `content_tag` function? Or do we want the `link` function to transform that value?
Edit:
I do think transforming w/in link could be nice, because that would allow us to clear the invalid URL instead of raising (which becomes a DoS as …

Whitelist accepted URI schemes

---

lib/phoenix_html/form.ex

The documentation listed `:value` and `:label`, while the code expects `:key` and `:value`.

Fix expected option keyword list keys in docs

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Continuation of #142. Addresses some of the feedback @josevalim gave there:
* Tests added for `Date`, `NaiveDateTime`, and `Time` values passed to `*_input` functions
* Conversion of these values to valid strings following MDN [date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date), [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local), and [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) specs
I'm not sure about the input value conversion code, feels a bit clumsy still, but it makes the tests pass, which was my first concern. I'm still fairly new to Elixir, feedback on code style is much appreciated here!
Feedback not (yet) addressed:
* Decided not to rename `datetime_local_input` to …

Add date, datetime-local and time input types

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This PR addresses issue #171, which I have experienced myself yesterday.
This pull request escapes the value option of form inputs to ensure that it gets represented properly in the generated HTML.
The HTML semantics of representing true attributes by repeating the key in the value (such as `disabled="disabled"`) cause some confusion on the value attribute, which would be represented as `value="value"` instead of `value="true"`.

Escape value of form input tags

---

lib/phoenix_html/form.ex
lib/phoenix_html/tag.ex
test/phoenix_html/form_test.exs
test/phoenix_html/tag_test.exs

Fixes https://github.com/phoenixframework/phoenix_html/issues/182
I also updated the helper tags so that the current output of using `checked="checked"` does not change. Direct use of these tags would change, however. I also updated tests and doctests to reflect this.
HTML5 boolean attributes can come in several forms.
These mean checked is true:
```
<checkbox checked="checked">
<checkbox checked="">
<checkbox checked>
```
This means checked is false:
```
<checkbox>
```

Add support for html5 boolean attributes to content_tag and tag.

---

lib/phoenix_html/form.ex
lib/phoenix_html/form_data.ex
test/phoenix_html/form_test.exs

Sometimes users need a way to create a
form that does not wrap params inside a
named param. This commit removes the
:as requirement. Forms without the :as option
will no longer have an id generated and the form
inputs will also forgo automatic id generation.

No longer require the :as option.

---

lib/phoenix_html/form.ex

Hi, probably [this PR](https://github.com/phoenixframework/phoenix_ecto/pull/95) should be accompanied by documenation update (regarding form errors) in this repo.

Update Form docs: mention :ignore action in "A note on :errors" section.

---

lib/phoenix_html/format.ex
test/phoenix_html/format_test.exs

resolves #190
This PR adds support for `\r\n` (Carriage Return & Line Feed) in [`text_to_html/2`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Format.html#text_to_html/2).

Support carriage return in text_to_html

---

lib/phoenix_html.ex
test/phoenix_html_test.exs

U+2028 and U+2029 is currently escaped using html escape sequences instead of js escapes, which this PR changes.
It also adds an escape for the U+0000 null character, which is invalid within html script tags.

JS escape fixes for uncommon whitespace and null

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Made a `input_id/3` just so it's easier to generate `for` attribute on labels. Maybe it makes sense to expand `label` to allow value passing. Not sure. One thing at the time.

Fixing id generation on radio buttons. fixes #194

---

lib/phoenix_html/form.ex
lib/phoenix_html/form_data.ex
test/phoenix_html/form_test.exs

Seems like `input_value` / FormData implementations were the only thing really relying on atom keys. The rest were either using `input_value` or doing `Atom.to_string` anyways.
I'd expect this would need `phoenix_ecto` to be updated as well.
Regarding to #197

Enable string keys to be usable with forms

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

- This bug shows up when using multiple_select with an unnamed form.
- Function spec indicates that input_name returns a String.

input_name should return a String when passed an unnamed form.

---

priv/static/phoenix_html.js

When creating a link with the `link` Phoenix helper, I would expect the `target` attribute to work seamlessly with any HTTP method.
Right now the `target` attribute only works with the GET method because it's not passed to the generated form when using another method.
I'm working on an admin area in Phoenix where I need to call an action with POST and would like to open the result in a new tab using `target: "_blank"`, this small change allows me to do that and I now get the same `target` behaviour for any HTTP method...
Thanks!

JS : use the target attribute of the link on the generated form

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs
test/phoenix_html/tag_test.exs

- Allow truncation precision to be configured.
- Get value from input_value to perform truncation in case value was not
specified in opts. <- This fixes the inconsistencies with the input value.
- Run `mix format` (Elixir 1.6.3)

Fix inconsistencies with time input.

---

lib/phoenix_html/link.ex
test/phoenix_html/csrf_test.exs
test/phoenix_html/link_test.exs

Changes for issuee #207 
Before the change every href attribute got set to `#` in the link helper if the method option isn't `:get`. This PR changes the current behaviour to set the href attribute to the destination address. That shouldn't have any side effects because both link to the current page.

Replace hash symbol with destination address in link helper

---

lib/phoenix_html/form.ex

Trailing `end` is not formatted correctly

fix datetime_select documentation

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This change allows ISO 8601 formatted strings to be passed as the value for date inputs.
Specifically, we're have an issue where we're passing an ISO 8601 string to a `date_select`.

Support ISO 8601 formatted strings for date values.

---

lib/phoenix_html/link.ex
priv/static/phoenix_html.js

Coming from Rails, and seeing that Phoenix has support for confirming actions with the `data-confirm` attribute, I naturally assumed that this would work with buttons as well. Turns out it does indeed work with buttons, but maybe that's just an undocumented accident. It works because the JS does not check the element type, it is only looking for the `data-method` attribute. 
Unfortunately, that also means that it will _not_ work with standard form submit buttons, because these lack the aforementioned `data-method` attribute. I find it very useful to have this option in full fledged forms though. I often find myself using a button first to sketch out a feature, then I find out later that we need to send additional data via form, so the button gets replaced with a form. Although the …

Allow data-confirm with submit buttons

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Fixes #222 
When `input_id/2` is passed a form with no `id`, it now returns the name of the field rather than `nil`.

Make input_id/2 return the field name when the form has no id

---

lib/phoenix_html/link.ex
priv/static/phoenix_html.js

This change does allow for two things 
* People can customize the data-confirm behaviour:
```javascript
// document.body, so it's executed before the default of phoenix_html
document.body.addEventListener('phoenix.link', function (e) {
// Prevent default behaviour
e.stopPropagation();
// Introduce alternative behaviour
var message = e.target.getAttribute("data-confirm");
if(!message){ return true; }
vex.dialog.confirm({
message: message,
callback: function (value) {
if (value == false) { e.preventDefault(); } 
}
})
}, false);
```
* Or add their own logic besides the phoenix data-confirm default behaviour (https://github.com/phoenixframework/phoenix_html/issues/206):
```javascript
window.addEventListener('phoenix.link', function (e) {
// Introduce custom behaviour
var message = …
```

Configurable and extendable data-confirm behaviour

---

priv/static/phoenix_html.js

`link` is not defined. The `dispatchEvent` should be called on the event target.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent

Fix typo 'link' instead of 'element' on click handler

---

lib/phoenix_html/form.ex
lib/phoenix_html/form_data.ex
test/phoenix_html/form_test.exs

When creating a form with the conn instead of with a changeset struct, there is no easy way of displaying error messages.
This is an attempt to make that easier by allowing `:errors` as an option to `form_for/4`.
In the controller:
```ex
def my_post_method(conn, params) do
case do_stuff(params) do
{:ok, object} -> render(conn, view_template)
{:error, reason} -> render(conn, view_template, errors: reason)
end
end
```
and in the template
```eex
<%= form_for @conn, "/do_stuff", [errors: @conn.assigns[:errors]], fn f -> do %>
<%= text_input f, :field %>
<%= error_tag f, :field %>
<% end %>
```
where `error_tag` is the custom function as mentioned in the [migration guides](https://gist.github.com/chrismccord/557ef22e2a03a7992624).

add errors in the conn to the form

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

fixes https://github.com/phoenixframework/phoenix_html/issues/232
Sometimes we don't want to send values from unchecked checkboxes to the server (e.g. when using a filter form and GET requests).
This PR allows developers to set the option `hidden_input: false` to not generate the hidden input. This way, the value will not be sent to the server if the checkbox is unchecked.

Add option to not send values from unchecked checkbox

---

lib/phoenix_html/form.ex

Super small change but I tripped over the documentation a few times since the first param is parsed and displayed as `name` although it can be `form` or `name`. The documentation says as much but then again, who reads documentations right? 😅

Optimize documentation for `Form.HTML.input_name/2`

---

lib/phoenix_html/form.ex

fixes dialyzer warning
Guard test __@1::{_,[{atom(),_}]} =:= 'false' can never succeed

remove match that cannot succeed

---

lib/phoenix_html/form.ex

Fixes dialyzer warning
```
The inferred return type of to_form/2 (#{'__struct__':='Elixir.Phoenix.HTML.Form', 'action':='nil', 'data':=#{}, 'errors':=_, 'hidden':=[], 'id':=_, 'impl':='Elixir.Phoenix.HTML.FormData.Plug.Conn', 'index':='nil', 'name':=_, 'options':=[{atom(),_}], 'params':=_, 'source':=atom() | #{'params':=_, _=>_}}) has nothing in common with #{'__struct__':='Elixir.Phoenix.HTML.Form', 'action':=binary(), 'data':=#{atom() | binary()=>_}, 'errors':=[{atom(),_}], 'hidden':=[{atom(),_}], 'id':=binary(), 'impl':=atom(), 'index':='nil' | non_neg_integer(), 'name':=binary(), 'options':=[{atom(),_}], 'params':=#{binary()=>_}, 'source':=_}, which is the expected return type for the callback of the 'Elixir.Phoenix.HTML.FormData' behaviour
```
see …

fix dialyzer complaining about nil action in to_form

---

lib/phoenix_html/form.ex
lib/phoenix_html/tag.ex

As seen [here](https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e#add-a-routes-alias-and-update-your-router-calls)
Router Helpers are no longer imported but aliased. Thus phoenix_html docs should be updated.

updated phoenix_html docs referring the changelog of phoenix v1.4

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

A couple of the other HTML functions allow passing in HTML safe tuples directly, in lieu of text. This PR adds the same functionality for the `label/4` function.
With this, you can do something like:
```elixir
<%= label @applicant_form, :additional_info, {:safe, "Additional <span>Information</span>"} %>
```
On the intent itself - I can agree that passing in HTML as a `:safe` tuple directly is not good idea. As mentioned, I've often overloaded the `text` arg in `link(text, opts)` to allow HTML (not realizing that the `link/2` function allows `do` blocks as well.
The only good reason for merging this is in because we usually passthrough the `text` argument eventually to `html_escape`, which is responsible for making this value usable. It seems arbitrary and inconsistent for some APIs to …

Implement ability to pass in HTML safe strings to label/4

---

lib/phoenix_html/form.ex

As mention in commit deprecation warning referes to the deprecated function itself

[FIX] deprecation warning referred to deprecated function

---

lib/phoenix_html.ex
test/phoenix_html_test.exs

At the time of the implementation of the javascript_escape function backticks weren't an issue as the string interpolation syntax was not broadly supported in javascript. This is now widely used and thus will introduce a vulnerability of XSS attacks.

escape backticks in javascript_escape/1

---

priv/static/phoenix_html.js

prevents downstream listeners from receiving the canceled click

Stop event propagation when cancel is clicked

---

lib/phoenix_html/form.ex

Closes #239
One small problem with current approach was that docs showed both spec clauses in docs for form_for/3 which was supposed to be only about the variant without anonymous function. See https://github.com/phoenixframework/phoenix_html/commit/cae0f75e51fe53de8edb783173790f235cb74604 for more details. When I removed the clause, however, dialyzer complains again, so it needs to be there.

Fix typespec for form_for/2-3

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Fix an issue with datetime_local_input, the date_time does not get formatted if the value is not explicitly set.

updated datetime_local_input to format default form value if if no value is explicitly set

---

lib/phoenix_html/form.ex
lib/phoenix_html/form_data.ex
test/phoenix_html/form_test.exs

Fixes #258
Continue the @LostKobrakai work https://github.com/phoenixframework/phoenix_html/pull/259

Allow `inputs_for` to skip hidden fields for more control over the final markup

---

lib/phoenix_html/tag.ex

1. `Routes.static_path/1` should be `Endpoint.static_path/1`.
2. `static_path` only accepts paths with a leading `/`.
3. Example output better matches real output in latest Phoenix.

Fix img_tag/2 examples

---

lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs

For responsive `<img>`s, alternate files can be supplied by the `srcset` attribute.
```html
```
This pull request supports stringifying `srcset` values from a map or list.
```elixir
img_tag("/logo.png", srcset: %{"/logo.png" => "1x", "/logo-2x.png" => "2x"})
img_tag("/logo.png", srcset: [{"/logo.png", "1x"}, {"/logo-2x.png", "2x"}])
```
Support for stringifying `sizes` was considered because the algorithm is identical, but `sizes` is likely hard-coded whereas `srcset` is generated from multiple `Routes.static_path`s.
```html
srcset="/logo-100.png 100w, /logo-200.png 200w"
sizes="(min-width: 100px) 50vw, 100vw">
```
So simply passing `sizes: "(min-width: 100px) 50vw, 100vw"` here would work.

Add :srcset option to img_tag helper

---

.travis.yml

As also noted [over here](https://github.com/phoenixframework/phoenix_html/pull/268#issuecomment-522332831), installing OTP 18.3 on Travis no longer works due to the release no longer being available at the URL Travis tries to download it from.
Given how relatively ancient OTP 18 is, I guess it might make sense to simply stop supporting it.

Disable testing on OTP 18

---

lib/phoenix_html/form.ex
lib/phoenix_html/tag.ex
test/phoenix_html/csrf_test.exs
test/phoenix_html/form_test.exs
test/phoenix_html/tag_test.exs

The hidden `_utf8=✓` form field hasn't been needed since IE 8, and given that browser is now three years in the grave, it might be time to remove this.
Rails, where this concept came from, disabled this last year: https://github.com/rails/rails/pull/32125
This MR does not remove `accept-charset="UTF-8"`. That might also be superfluous, but I haven't researched how well browsers handle that.

Remove :enforce_utf8 option

---

lib/phoenix_html/link.ex

https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/link.ex#L206
it is checking for atom.

use atom instead of string

---

lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs

Closes #281 
This removes the `is_atom` guard clauses on the `content_tag` functions allowing strings to be passed.
content_tag("custom-component", "Hello")

Allow strings in content_tag

---

lib/phoenix_html/form.ex

It listed opts twice like so `submit(opts, opts \ [])`, which was confusing at least to me.
**Screenshot of new version:**
**Screenshot of old version:**

Improve docs for Phoenix.HTML.Form submit/2 

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

When a checkbox is disabled, it doesn't send its value when the form is submitted - but the still-active hidden input DOES. The result is that a disabled checkbox will always submit as its unchecked value (`"false"` by default).
See also https://github.com/rails/rails/issues/1953 where a similar helper function had the same bug with the same fix.
Not 100% certain about the formatting on the change in `form.ex`; that's what running `mix format` gave me but there's a bunch of other files that that wants to change as well...

Disable hidden input for disabled checkboxes

---

lib/phoenix_html/form.ex

v2.14.11 introduced a regression. Now a valid code
```
<%= inputs_for f, :my_field, fn f2 -> %>
<div class="form-group">
<%= label f2, :name, class: "control-label" %>
<%= text_input f2, :name, class: "form-control" %>
<%= error_tag f2, :name %>
</div>
<% end %>
```
fails to dialyze with
```
The function call will not succeed.
Phoenix.HTML.Form.inputs_for(_f :: any(), :my_field, (_ -> {:safe, [any(), ...]}))
breaks the contract
(t(), field(), Keyword.t()) :: [t()]
```

Fix inputs_form spec

---

lib/phoenix_html/form.ex

Follow up to the discussion between @chrismccord and @jayjun during the night on the Elixir slack, it seemed this is not meant to be hidden from user, but is not documented.
It now is.

Document the index field in Phoenix.HTML.Form

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

According to 
```elixir
@type field :: atom | String.t()
```
the `inputs_for/3` is missing `is_binary(field)` guard. 
This PR adds the guard so it's consistent with the rest of module's functions which typically have `is_atom(field) or is_binary(field)` guard that allow passing binary field.

Fix inputs_for/3 is missing is_binary(field) guard

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs
test/phoenix_html_test.exs

Closes #303 
This PR allows to add extra html attributes to a select option that has been generated with the `prompt` option.
The following code
```elixir
select(:user, :role, ["Admin": "admin", "User": "user"], prompt: [key: "Choose your role", disabled: true])
```
will generate this HTML output:
```html
<select id="user_role" name="user[role]">
<option value="" disabled>Choose your role</option>
<option value="admin">Admin</option>
<option value="user">User</option>
</select>
```
Feel free to ask me for modifications if you think I could better code this behaviour, as this is my first PR in the Elixir world :partying_face:
It also seems that `mix format` corrected a typo in a test file. I can do a separate PR if needed.

Allow extra html attributes with select option generated with prompt

---

lib/phoenix_html/form_data.ex
test/phoenix_html/form_test.exs

This commit will prefix the form id in its inputs id as form_for/4 does.
It avoid issues when having multiple forms on the same page, you can see more info about it here:
https://github.com/phoenixframework/phoenix_live_view/issues/1014

Prefix form id when it is present in form_for/3

---

lib/phoenix_html/form_data.ex
test/phoenix_html/form_test.exs

The last commit takes the ID from the opts so the form will never render the ID anymore. This commit fix that and ensure id will be preset with tests.

Ensure form still have id when present

---

lib/phoenix_html.ex

Include the file in compile warnings within the ~E and ~e sigils, fixing https://github.com/phoenixframework/phoenix_html/issues/311
Before:
After:

Display file on compile warning in sigil

---

lib/phoenix_html/form.ex

HTML5 allows an `<input>` to specify the form that it is associated with by using the [form](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefform) attribute. This works fine for every Phoenix.HTML.Form function I've used except `checkbox/3`'s hidden input for the unchecked value. This change simply copies the `form` attribute from the checkbox when it creates the hidden unchecked input, so that it is sent to the correct form.
An example. If I have this template:
```elixir
<%= f = form_for :foo, "/foo", id: "myform" %>
</form>
...
<%= checkbox f, :is_admin, form: "myform" %>
```
it will produce this HTML:
```html
<form action="/foo" id="myform" method="post">
</form>
<input name="foo[bar]" type="hidden" value="false">
<input form="myform" id="foo_bar" …
```

Honor the `form` attribute when creating hidden checkbox input

---

priv/static/phoenix_html.js

Makes it so that the behavior of modifier key clicks (cmd/ctrl + click, shift + click) on links with a `:method` opt more closely matches that of normal links. Does so by adding `target="_blank"` to the hidden form when a modifier key is used.
Preference is given to the existing link target, if present.
Chrome: Matches normal links exactly
Safari: cmd + click matches exactly, shift + click opens a new window (instead of adding to reading list)
Firefox: Both cmd + click and shift + click open a focused new tab
The behavior doesn't match normal links exactly, however it tends not to be far off. Whereas before, the link would always result in navigation in the current browser tab.
Closes #319

Respect modifier key clicks for links with :method opt

---

lib/phoenix_html/link.ex

According to the W3C specification the query parameters in the action
field of a form will be stripped when submitting a form with the method
get.
Closes: #317

Add documentation about query parameters for button/2

---

CHANGELOG.md
lib/phoenix_html/safe.ex
test/phoenix_html/safe_test.exs

Most browsers are fine with with the non-iso-standard to_string we provide in Elixir that does not include the T but some browsers, Safari in particular, will choke and blow up. Using the ISO standard as a default and asking the user to format or choose their own representation is a more clear choice. 
This change does regress and will not use a users configured timezone abbr by default but they can simply call the function to fix that. 
(Please ignore the branch name)

Use to_iso8601 as the standard implementation for safe dates and times

---

lib/phoenix_html/tag.ex

The `tag` variable was passed around but was unused so I have removed it.
Thank you for reviewing.

Remove unused variable

---

lib/phoenix_html/form.ex

Just a small documentation update! I was really confused about how to use something like `gettext` to translate labels. So I wanted to add a little documentation about how to actually specify the text to prevent field inference + an example of it.

Add docs and example for Form.label/4

---

lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs

This PR adds a new function called `attributes_escape/1` that will be used by the new template engine I'm working on. I'm not sure this function should be placed in the `Tag` module since neither `tag` nor `content_tag` use it. However, I believe they should use it for consistency. The problem is that, currently, the implementation sorts the attributes, which makes no sense for the new engine as it generates groups of attributes separately based on their types (static key/value, static key + dynamic value and dynamic key/value). 
I can either move this function to someplace else or change the implementation of `tag` and `content_tag` to use it. The latter might break existing code if, for any reason, the order of the attributes was taken into account, for instance, in tests.

Add Tag.attributes_escape/1

---

lib/phoenix_html.ex
test/phoenix_html_test.exs

Similar to existing aria-* and data-* attributes support, allow for
passing nested phx-* attributes to tags.

Support nested phx-* attributes

---

lib/phoenix_html/form.ex

closes #363
`phoenix_html` doesn't depend on `phoenix_live_view` but it seems that this is the replacement for the deprecated `~e` sigil

Update Form.datetime_select/3 example to use H sigil

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This is particularly useful for fields of type `{:array, Ecto.Enum}` which would fail to be converted to HTML:
```
** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: :a
```
I imagine that converting the items of `value` to HTML and setting `checked` according to if `checked_value in value` would be deemed too much.
I'm happy to compute `checked` myself, but I believe that having to pass a bogus `value` parameter for the code not to crash is a bug.
Note that this PR introduces a potential behavior change for:
```
checkbox(..., value: "a", checked_value: "a", checked: false)
````
Current behavior overrides the `checked` to `true` while this PR maintains the explicitly given value of `false`. It …

Have `checkbox` use `value` only when `checked` needs to be determined

---

lib/phoenix_html.ex
lib/phoenix_html/tag.ex
test/phoenix_html/tag_test.exs
test/phoenix_html_test.exs

Ref https://github.com/phoenixframework/phoenix_html/issues/372

Move Phoenix.HTML.Tag.csrf_token_value to Phoenix.HTML

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Previously, the same ID would be generated for all checkboxes.

Fix `checkbox` generating wrong `id` parameter for multi checkbox case

---

lib/phoenix_html/safe.ex

While looking at the changes made in #383 I noticed `defdelegate` being used in the implementations of `BitString`, `Time`, `Date` and `NaiveDateTime` and thought it would be nice if the one for `Integer` would do the same.
And, since the current implementation for `Float` is just the code of [`Float.to_string/1`](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/float.ex#L562) copied over, I delegated to that one too.
Feel free to close if you don't like it, just a quick thought I had. ☺️

Use `defdelegate` for HTML.Safe implementations of Integer and Float

---

.github/workflows/ci.yml

I think the reason why `master` is currently failing is because...
GitHub Actions switched `ubuntu-latest` from `ubuntu-20.04` to `ubuntu-20.04` in the last month or so
(https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) and the currently used OTP versions in `ci.yml` are not compatible with what comes in `ubuntu-22.04` by default
(https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp).

Fixes CI runs

---

lib/phoenix_html/tag.ex
test/phoenix_html/csrf_test.exs
test/phoenix_html/form_test.exs
test/phoenix_html/tag_test.exs

- fix: add hidden attr to csrf inputs https://github.com/phoenixframework/phoenix/issues/5197

fixes csrf token and _method inputs visibility

---

lib/phoenix_html/form.ex

Fixes implementations (like phoenix_ecto) that expect a field atom to derive value.

Use field atom for input_value

---

CHANGELOG.md

The titles/versions in the changelog are indented inconsistently, and the last versions (>= 3.0.0) don't appear in [the hexdocs](https://hexdocs.pm/phoenix_html/changelog.html). This should fix it. Got my attention with the last release (first one that includes changelog I think).

Fix markdown titles in changelog so they appear in the TOC of docs

---

lib/phoenix_html/form.ex

Changes `"checkboxes"` to `"checkbox"` to match the expected argument value.

docs: fix argument value

---

lib/phoenix_html/form.ex

>  field. Forms backed by an `Ecto.Changeset` only support atom field names.
The form handles the string fine, but the ecto formdata implementation raises on non atom keys.
Per:
```elixir
defp fetch(%{errors: errors} = form, field, field_as_string) do
{:ok,
%Phoenix.HTML.FormField{
errors: for({^field, value} <- errors, do: value),
field: field,
form: form,
id: input_id(form, field_as_string),
name: input_name(form, field_as_string),
value: input_value(form, field) # <- THIS CALL
}}
end
```
and
```elixir
def input_value(_data, _form, field) do
raise ArgumentError, "expected field to be an atom, got: #{inspect(field)}"
end
```
https://github.com/phoenixframework/phoenix_ecto/blob/c68548d8d2dd904cbb7e43cf10b11076b92df91d/lib/phoenix_ecto/html.ex#L121-L123
>  It is possible to "access" …

Document form[field] access quirks

---

lib/phoenix_html/form.ex

Found a couple typos in the docs and cleaned them up. Also changed some wording to improve readability.

docs: fix some typos and improve readability

---

lib/phoenix_html/form.ex

This was discussed in the Elixir Slack recently and I think it's worth making the docs clearer because it was a big point of confusion for me:

Update docs to note that form/1 is preferred over form_for/4

---

priv/static/phoenix_html.js

We recently ran into a conflict with a third party js library that uses the `data-method` attribute on elements to signal which function should handle its events. The javascript bundled with `phoenix_html` also does a HTTP POST together with this non-sensical method attribute as a side effect.
The docs here might be misleading:
```
Support data-method="patch|post|put|delete" attributes, which sends the current click as a PATCH/POST/PUT/DELETE HTTP request. You will need to add data-to with the URL and data-csrf with the CSRF token value
```
as that would suggest that only valid HTTP request types are being handled, while instead every custom method results in a POST as well.
So I decided to restrict this to only trigger click handling when the `data-method` is indeed one of the …

Require a data-to with the data-method before the click handler triggers a HTTP request 

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This allows you to add separators to option lists, as described [here](https://developer.chrome.com/blog/hr-in-select).

Add <hr/> support to options_for_select

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

Allow keyword list options to use nil as key and/or value 

---

lib/phoenix_html/form_field.ex

Adds a type to Phoenix.HTML.FormField, allowing use of the type instead of the struct in typespecs
Related Credo warning: [SpecWithStruct](https://hexdocs.pm/credo/Credo.Check.Warning.SpecWithStruct.html)

Add type to Phoenix.HTML.FormField

---

lib/phoenix_html/safe.ex
test/phoenix_html/safe_test.exs

I was creating a form which had a set of options, the values being durations
```elixir
<.input
label="Duration"
field={@form[:duration]}
type="select"
options={[
{"Daily", Duration.new!(day: 1)},
{"Weekly", Duration.new!(week: 1)},
{"Monthly", Duration.new!(month: 1)},
{"Yearly", Duration.new!(year: 1)}
]}
/>
```
`Duration` has `to_iso8601` and `from_iso8601` functions so I assumed this would work like `Date` and `Time` does (auto converts to ISO), but `Phoenix.HTML.Safe` hadn't been implemented for Duration causing this error: `protocol Phoenix.HTML.Safe not implemented for type Duration (a struct).`
This PR adds the `Phoenix.HTML.Safe` implentation. Their might of been a reason why this wasn't added originally though, but im not too sure why that could be?

Add `Phoenix.HTML.Safe` to Duration

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

This PR allows custom option tags for the `options_for_select/2` function. This is useful for integrating third party libraries like @tailwindcss/elements.

feat(custom option tags): allow custom tags in options_for_select

---

lib/phoenix_html/form.ex
test/phoenix_html/form_test.exs

If I try to use a select with struct values, I get an error because of an `is_map` check, and assumes that it is an option group.
We should be able to pass as values any struct that implements the `Phoenix.HTML.Safe` protocol.
- added a struct check
- added a new test assertion that fails without this fix:
```
1) test options_for_select/2 simple (Phoenix.HTML.FormTest)
test/phoenix_html/form_test.exs:262
** (Protocol.UndefinedError) protocol Enumerable not implemented for type DateTime (a struct).
This protocol is implemented for the following type(s): Date.Range, File.Stream, Function,
GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
Got value:
~U[2025-01-01 06:30:00.000000Z]
code: assert options_for_select([
{"Open", ~U[2025-01-01 06:30:00.000000Z]}, …
```

Allow structs as select option values
