lib/phoenix_html/link.ex, test/phoenix_html/link_test.exs
Did you have something like this in mind with #2?
=> Add support for a `do` block in `Phoenix.HTML.Link.link/2`

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Closes https://github.com/phoenixframework/phoenix_html/issues/9
=> Add label/4 tag

lib/phoenix_html/form.ex
=> Fix typo in comment docs

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
```erb
<%= reset "Clear", class: "btn" %>
#=> <input type="reset" value="Clear" class="btn">
```
=> Add reset input in order to reset forms field to their original state

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Add the option to use multiple select form with the select helper
=> add multiple select support

lib/phoenix_html.ex
As discussed here:
https://github.com/phoenixframework/phoenix_html/commit/6ad3a1d7960891a468d54636054a98e11dfb5111#commitcomment-13102060
=> Clarify ~e interpolation error

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Hello,
I needed a color input for a project of mine and didn't find any in Phoenix, so I added one manually. Here is the PR if you wish to merge it.
Thanks for your work!
=> Add an HTML5 color input

test/phoenix_html/safe_test.exs, test/phoenix_html_test.exs
Wasn't where I expected it when I wanted to modify that module.
Also taking the opportunity to make the remaining test names more consistent.
=> Extract Safe to own tests

lib/phoenix_html/link.ex, test/phoenix_html/link_test.exs
=> added rel=nofollow auto generation for non-get links

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
=> Form value/id/name helpers were made public.

lib/phoenix_html/form.ex
credit to @trinode for catching it
=> Date should use year instead of hour

priv/static/phoenix_html.js
=> Use event delegation in phoenix_html.js #75

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Right now it renders a input tag for submit I think it should be a button, buttons are much easier to style
=> render button tag for submit instead of input

lib/phoenix_html/form.ex
https://www.reddit.com/r/elixir/comments/4t5d6n/question_in_a_form_what_does_the_as_atom_do/
=> Improving docs for reddit question. 

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Thanks for making me do this @josevalim now I get why `[]` needs to be there.
Closes #114
=> Support multiple attribute on file_input (#114)

lib/phoenix_html.ex, lib/phoenix_html/form.ex
Hello :)
This PR fixes really minor formatting issues and a typo in the documentation.
=> Minor formatting/typo fixes in the documentation

lib/phoenix_html/form.ex
- See: https://github.com/phoenixframework/phoenix_ecto/issues/79
=> Clarify documentation for changeset errors

lib/phoenix_html/tag.ex
This may be a common pitfall for some
=> Adding `@conn` for the `static_path/2` implementation

lib/phoenix_html/form_data.ex
=> Link to t:Phoenix.HTML.Form.t/0 in Phoenix.HTML.FormData

lib/phoenix_html.ex
Similar to https://github.com/phoenixframework/phoenix_live_view/pull/567
=> Pass :indentation to EEx

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Fixes https://github.com/phoenixframework/phoenix_html/issues/291
TODO:
=> Add Phoenix.HTML.Form.inputs_for/3

lib/phoenix_html/link.ex, test/phoenix_html/link_test.exs
=> Allow %URI{} to be passed to link/2 and button/2 as :to

lib/phoenix_html/link.ex
Jose merged the last one on #309 too fast 😅
=> Add a URI example to link/2 documentation

lib/phoenix_html/link.ex
It does not (no longer?) generates an actual HTML form, but rather uses
Javascript to build one dynamically and submit.
=> Correct documentation of Link.button/2

lib/phoenix_html/form.ex
Closes #343 
This PR updates the example to match the real returned value of the label do block.
=> Fix label do block example

lib/phoenix_html/tag.ex
Related to: phoenixframework/phoenix_live_view#1559
=> attributes_escape/1 accepts a map

lib/phoenix_html/form.ex
Hello! I _think_ this fixes https://github.com/phoenixframework/phoenix_html/issues/345.
Follow-up to https://github.com/phoenixframework/phoenix_html/commit/de1a75056fc2ff6c1627f60153dfb15c90d16bf8
The Dialyzer errors go away at least :)
=> Add spec to Form.form_for/3 in order to fix Dialyzer issues

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
Something like this?
resolves #359
=> support rendering hidden inputs for list of values

lib/phoenix_html/form.ex, test/phoenix_html/form_test.exs
=> Support string fields in input_changed?/3
